### PR TITLE
Implement optional backend support, fix few other issues

### PR DESCRIPTION
**Pull request by ahmubashshir**
- make: Allow disabling backends at compile-time
- make: Call generator with generated filename
- wayland: Only request a version of wl_output that we actually need
- wayland: Show error on ftruncate failure
- wayland: Use system wayland protocol definitions
- nix: Update flakes dependencies
- nix: Use a common file for declaring dependencies
- make: Simplify and clean up backend selection

### CODE REVIEW

**Comment by ahmubashshir** [comment]
This pr fixes #128 too 😀 But you have to reset again to merge painlessly 😫

Here you go
```sh
# to revert
git revert 6005530
git revert 872f0ca
git revert 9abd809 -m1
# to drop offending commits
git reset --hard c937437

# use either revert or reset, not both.
```

**Comment by ahmubashshir** [comment]
@MrGlockenspiel, this pr fixes #128 too 😀 But you have to reset again to merge painlessly 😫

Here you go
```sh
# to revert
git revert 6005530
git revert 872f0ca
git revert 9abd809 -m1
# to drop offending commits
git reset --hard c937437

# use either revert or reset, not both.
```

**Comment by MrGlockenspiel** [comment]
thank you so much, especially for the instructions because i can barely wrap my head around git sometimes

**Comment by MrGlockenspiel** [comment]
@ahmubashshir im not sure if i broke something or what but the wayland backend is causing issues, specifically with `wlr-layer-shell-unstable-v1.h` seeming to not generate

**Comment by ahmubashshir** [comment]
@MrGlockenspiel it's generated on the fly... as it's an intermediate dependency(dependency of wayland.o), it's generated before compiling wayland.c and removed after compilation automatically.

It's done this way so that it can be generated automatically each time.

wayland/wlr-layer-shell-unstable-v1.h

clean up

**Comment by ahmubashshir** [comment]
@MrGlockenspiel You probably didn't drop the offending commits...
Apply this patch with `git apply` to fix this (run `git apply`, paste the patch, press <Control>D to close input and apply this patch).

```diff
diff --git a/src/wayland/wayland.c b/src/wayland/wayland.c
index 5833e36..92137fe 100644
--- a/src/wayland/wayland.c
+++ b/src/wayland/wayland.c
@@ -12,7 +12,7 @@
 
 #include <cairo.h>
 
-#include <wlr-layer-shell-unstable-v1.h>
+#include "wlr-layer-shell-unstable-v1.h"
 
 #include "wayland.h"
 #include "log.h"
```

**Comment by MrGlockenspiel** [comment]
ok yeah it works now :sweat_smile:

**Pull request merged**
