### PR TITLE
Implement presets and preset selector

### PR DESCRIPTION
**Pull request by ahmubashshir**
- i18n: Implement text presets
- i18n: Implement diss-ms preset for en_US
- i18n: Add macro helper header
- i18n: Document the helper macros
- i18n: Clean up source
- misc: Update ARGS.md with preset arg docs

### CODE REVIEW

**Comment by ahmubashshir** [comment]
@MrGlockenspiel @Ruby-Dragon please review this 🥺

**Comment by Ruby-Dragon** [comment]
seems good to me tbh.

**Comment by Ruby-Dragon** [comment]
I need to actually try it - will probably do this weekend

**Comment by ahmubashshir** [comment]
On Fri, Sep 2 2022 at 10:01:04 AM -07:00:00, Ruby-Dragon 
***@***.***> wrote:
> I need to actually try it - will probably do this weekend

Cool beans :3

	Mubashshir

**Comment by Ruby-Dragon** [comment]
well it seems that grub has been broken by a new update, I will check this out once i get an live usb to fix the issue

**Comment by Ruby-Dragon** [comment]
ok I have tried it out and I think it works very well. Good job!

**Comment by MrGlockenspiel** [comment]
I've always wanted to activate my BSD on Linux, incredible

**Pull request merged**
