### PR TITLE
Use CMake instead of Makefiles

### PR DESCRIPTION
**Pull request by KyleFromKitware**

### CODE REVIEW

**Comment by Ruby-Dragon** [comment]
Would this interfere with the AUR and OBS packages? I dont know a lot abput either but a change like this seems like it would make at least the AUR package not work.

**Comment by KyleFromKitware** [comment]
Both of those packages could be modified to use CMake instead of Make. I'm not an expert on them, so someone else can feel free to contribute such a change. (I can put back the Makefiles so that they still work in the meantime.)

**Comment by ReperakDev** [comment]
I don't think CMake is really necessary in a project as small as this. Plus, it seems like shilling CMake, as I recognize Kitware as the developers of CMake.

**Comment by Ruby-Dragon** [comment]
The AUR release is not maintained by Mr. Glockenspiel, so we dont know if it will be updated

**Comment by MrGlockenspiel** [comment]
With a project this small, I think CMake would do more harm than help, especially as I don’t use it personally and know nothing about how it works

Open to hear other’s opinions however

**Comment by ReperakDev** [comment]
Very clunky and adds too much complexity. Also, despite claiming to be the holy grail of build systems, it does surprisingly little for you and is almost as "low level" as writing raw Makefiles. The only advantage I can see is that you can use other build systems (e.g. Ninja, Bazel), but it's not worth that.

**Comment by KyleFromKitware** [comment]
In my opinion, raw `Makefile`s are brittle, and tend to fall apart/get complicated when you try to do anything beyond the most basic use case of "compile a simple project with no dependencies and no configuration options on a single Unix-like platform using the default compiler, the default sysroot, and no compiler flags." Want to cross-compile or otherwise use something other than whatever `cc` is on your path? You'll almost certainly need to modify the `Makefile` by hand. Want to use a different sysroot? Same deal. Want to specify your own compiler flags? If you're lucky, the project recognizes `CFLAGS`, but if not, you'll need to modify the `Makefile`. Dependencies? They might work, as long as you don't try to use a hand-compiled dependency from your own staging sysroot. Configuration options? If you're not using a system like `Kconfig`, you'll need to either specify a flag every time you run `make` or modify the `Makefile` by hand. Windows support? Forget about it. Even this very simple project, which has only two source files and one header file, had to have two different `Makefile`s to support different platforms.

CMake solves all of these problems and more, with the project author not having to think about most of them, because they're automatically handled by the logic of `add_executable()` and friends. Personally, I'm at the point where I don't write raw `Makefile`s for even the most basic of projects, because I can write a `CMakeLists.txt` that expresses the same setup without having to even think about `.o` files and `CFLAGS` and such.

That being said, I realize most of these issues are not as much of a concern for such a small project. So, here's a justification that's more in line with the spirit of this project:

"Science isn't about WHY. It's about WHY NOT."

Great game and quote btw, been a fan for years :)

**Comment by Ruby-Dragon** [comment]
This project doesnt support windows at all

**Comment by ReperakDev** [comment]
I dislike having a separate Makefile for BSD. Nobody uses the BSDs.

**Comment by MrGlockenspiel** [comment]
It costs us nothing to support it so /shrug

**Comment by Ruby-Dragon** [comment]
I am now no longer opposed to this as the packages need to be updated anyways

**Comment by MrGlockenspiel** [comment]
The build steps are probably my biggest issue with CMake as well
Sure, its great for a large, complex project with many dependencies, but this? It seems like it would be more of an annoyance than a help here

**Comment by Ruby-Dragon** [comment]
True

**Comment by Piraty** [comment]
this project is just compiling 2 c files, the makefile is readable, there are not build-options. so no cmake please. If anything, use meson please.

**Comment by eli-schwartz** [comment]
> Even this very simple project, which has only two source files and one header file, had to have two different `Makefile`s to support different platforms.

I don't think it "had" to, tbh. The BSD makefile appears to be hooking into BSD's native ports framework? and as such I'd argue it isn't a Makefile to support a platform, it's a package recipe that happens to be a Makefile. The Linux equivalent of that Makefile.BSD isn't "Makefile", the Linux equivalent is "PKGBUILD" or "activate-linux.ebuild" or "activate-linux.spec" or "debian/rules".

I see no reason that the "Linux" Makefile cannot be used on BSD as well, if one prefers.

...

Why does this project need a BSD packaging recipe? I don't know -- why does it need "activate-linux.spec" which is also there? :)

...

> Want to cross-compile or otherwise use something other than whatever `cc` is on your path? You'll almost certainly need to modify the `Makefile` by hand.

... or use `$(CC)` instead of `cc`, which means it's okay since practically everyone already does this. It's even baked into GNU Make itself as a builtin rule.

> Want to use a different sysroot? Same deal. Want to specify your own compiler flags? If you're lucky, the project recognizes `CFLAGS`, but if not, you'll need to modify the `Makefile`.

Trivial, and already done by this project.

> Dependencies? They might work, as long as you don't try to use a hand-compiled dependency from your own staging sysroot.

This works flawlessly, as the Makefile already uses a package finder (pkg-config) to get dependencies, which supports sysroots fine.

> Configuration options? If you're not using a system like `Kconfig`, you'll need to either specify a flag every time you run `make` or modify the `Makefile` by hand.

Sure... but this is a "simple project" so it doesn't need those. :)

(By the way, you can do this in a Makefile too, just have the first build write out a config.mk)

> Windows support? Forget about it.

For projects that support Windows at the source level, it is of course important to support Windows at the build system level too.

> That being said, I realize most of these issues are not as much of a concern for such a small project.

s/most/all/ ?

Everything you mention is either a Make dealbreaker depending on project size, which is not a concern for a small project, or else something that isn't a concern for any project as long as *really easy* best practices are followed, which admittedly many people don't do, but then again, many people also write CMakeLists.txt which force-sets the compiler, the CFLAGS, and a variety of other things. So it's no surprise that they do the same thing in Makefiles.

~~Luckily build systems like Meson don't allow you to hardocde a compiler in meson.build~~

**Pull request closed without merging**
