### PR TITLE
X11 and logging related patches

### LINKED ISSUE #129: X11: Doesn't redraw after monitor wake-up
### Steps to reproduce:
1. Run this
2. Run `xset dpms force off` ; this puts active monitor to sleep.
3. Wake up monitor by moving mouse/pressing keyboard...

### Expected behavior
The watermark should be visible.

### What happens
The watermark disappears.

---
https://user-images.githubusercontent.com/24864366/179542670-b28db1b8-b706-4bf1-b106-4ccb1b36441d.mp4

### LINKED ISSUE #133: [BUG] verbose state isn't kept between files.
`static` modifier usage [here](https://github.com/MrGlockenspiel/activate-linux/blob/4c848f495ff0067f860d823b76e4c2e3af3d8e38/src/log.h#L4) was incorrect as `static` makes a private copy of the variable per file.

### PR DESCRIPTION
**Pull request by ahmubashshir**
- misc: Follow `linux` code style
- log: Fix logging and add few more log directive
- misc: Add more directive for pretty printing help text
- x11: Redraw overlay after display wake-up
- makefile: Compile only after file is modified
- misc: Use generated function to translate XEvent.type
- makefile: Check `-e` flag compatibility of echo 

Closes #133 
Closes #129

### CODE REVIEW

**Comment by AHOHNMYC** [comment]
Ah, the best sort of commits where most of files are changed because of no valuable reason (too smart IDE with custom code style) :D
(I like what you have fixed BTW)

**Comment by ahmubashshir** [comment]
> Ah, the best sort of commits where most of files are changed because of no valuable reason (too smart IDE with custom code style) :D (I like what you have fixed BTW)

You mean d9054dc? I did that because each file was different, tabs somewhere, space elsewhere, and my pre-commit hook didn't like it 🙃

So, ran astyle on all files before doing anything valuable so that I can commit without annoyance 🚀

P.S. I don't use any `too Smart IDE`(tbh not any IDE, they're bloat for most of the task) 😎 did everything with nano/sed/ack and tmux 🙃


image

**Comment by ahmubashshir** [comment]
P.S. I'll implement #132 and #135 in my next PR.

And guys from #58, try this and confirm if this PR solves your issue.

**Comment by MrGlockenspiel** [comment]
wait are these the same patches you emailed me? because i already merged those

**Comment by ahmubashshir** [comment]
> wait are these the same patches you emailed me? because i already merged those

Please drop those and merge this if possible 🥺

I accidentally ran `git send-email` before finishing `patch v2` formatting 😨

**Comment by MrGlockenspiel** [comment]
sorry im late, have been busy

ill get to that asap

**Comment by MrGlockenspiel** [comment]
wow i didnt break anything

**Pull request merged**
