### PR TITLE
Update activate_linux.c

### PR DESCRIPTION
**Pull request by asoji**
it's so fucking stupid please do not accept this

### CODE REVIEW

**Comment by MrGlockenspiel** [comment]
I am torn

**Comment by LizAinslie** [comment]
I approve the merging of this commit into a separate branch and will be glad to host builds

**Comment by asoji** [comment]
OH MY GOD LMAO

**Comment by asoji** [comment]
god this is amazing

image

**Comment by MrGlockenspiel** [comment]
the hardest choices require the strongest wills

**Pull request merged**
