### PR TITLE
Diss Microsoft

### PR DESCRIPTION
**Pull request by Ruby-Dragon**
Add -$ flag to change message to diss Microsoft. Only support en_US at the moment. Completes issue #137.

### CODE REVIEW

**Comment by AHOHNMYC** [comment]
Yeah I can easily imagine as Billy Gates, Microsoft, and Windows walking near your unlocked Linux PC and all of them are immediately dying from insult. Good PR.

**Comment by Ruby-Dragon** [comment]
ok time to fix merge conflicts

**Comment by Ruby-Dragon** [comment]
i think ima redo this, its not a lot of work tbh

**Comment by ahmubashshir** [comment]
Wouldn't it be better to implement this with presets?

preset|usage
:---|:---
`-P default`| platform default text
`-P darwin`| Show the darwin text
`-P bsd`| Show the bsd text
`-P micro$#!+` or `-P m$` | Diss M$

**Comment by Ruby-Dragon** [comment]
possibly, If I am just going to redo most of it I do not see why not

**Comment by ahmubashshir** [comment]
btw, you better do that after @MrGlockenspiel solves #128 and #141 conflict

**Comment by Ruby-Dragon** [comment]
an excuse for me to not work on it lol

**Comment by ahmubashshir** [comment]
@Ruby-Dragon, I've implemented [this](#issuecomment-1228718832) in <code>[ahm-forks:presets](https://github.com/ahm-forks/activate-linux/tree/presets)</code>

- Relevant commits:
  - Presets implementation: fd5e234
  - diss-ms Preset: 6986351

Check them and give feedback :3

**Comment by ahmubashshir** [comment]
> @Ruby-Dragon, I've implemented [this](#issuecomment-1228718832) in <code>[ahm-forks:presets](https://github.com/ahm-forks/activate-linux/tree/presets)</code>
> 
> * Relevant commits:
>   * Presets implementation: fd5e234
>   * diss-ms Preset: 6986351
> 
> 
> Check them and give feedback :3

@MrGlockenspiel, check this branch. I'm not proud of this hack even though this works... trying to make this shit better...

**Pull request closed without merging**
