### PR TITLE
makefile: Use the system provided wayland-scanner

### PR DESCRIPTION
**Pull request by Nefsen402**
Should build more reliably across more distributions that ship with
very old versions of wayland-scanner and wayland libraries.

### CODE REVIEW

**Comment by MrGlockenspiel** [comment]
I really hope i didnt break this

**Comment by MrGlockenspiel** [comment]
ok yeah i did

**Comment by ahmubashshir** [comment]
@MrGlockenspiel I'm currently working on this, check 69b378a

**Comment by MrGlockenspiel** [comment]
> @MrGlockenspiel I'm currently working on this, check [69b378a](https://github.com/MrGlockenspiel/activate-linux/commit/69b378a79af2d2a0d17cd539ca07e9f1767e9864)
> 
> btw, this(#128) is broken

Oh yeah i think messed it up real bad 💀

**Pull request merged**
