### PR TITLE
Improve handling of colors

### PR DESCRIPTION
**Pull request by ReperakDev**
I'm @MrGlockenspiel's friend so I get merge priority :trollface:

### CODE REVIEW

**Review by ReperakDev — COMMENTED** [review]
I have been informed that gotos are [very icky no good](https://youtu.be/SfJBshvLJe4) so I will fix

**Review by MrGlockenspiel — CHANGES_REQUESTED** [review]
Remove gotos i would be shamed for letting them in

**Comment by ReperakDev** [comment]
Threat neutralized. Moving out

**Comment by Ruby-Dragon** [comment]
why did you use goto in the first place?

**Comment by Ruby-Dragon** [comment]
also, this is pretty good and I think we should merge @MrGlockenspiel

**Comment by MrGlockenspiel** [comment]
yeah i just didnt have time to look through it before yet

**Comment by ReperakDev** [comment]
> why did you use goto in the first place?

A little late but it's because they're better in every way for error recovery. An oversimplified example is this:

```c
int do_various_shit()
{
    char *foo = malloc(sizeof(char) * 50);

    int bar = get_bar();
    if (!bar) {
        return 1;
    }
    // just pretend that we used bar ;)

    free(foo);
    return 0;
}
```

See the problem here? If get_bar fails, foo is never freed.

We could fix it like this:

```c
// snip
    int bar = get_bar();
    if (!bar) {
        free(foo);
        return 1;
    }
// snip
    free(foo);
    return 0;
// snip
```

But that's stupid and ineffcient.

Let's refactor it to use gotos.

```c
int do_various_shit()
{
    int ret_code = 0;
    char *foo = malloc(sizeof(char) * 50);

    int bar = get_bar();
    if (!bar) {
        ret_code = 1;
        goto err;
    }

err:
    free(foo);
    return ret_code;
}
```

Much better.

**Pull request merged**
