### PR TITLE
Relicense under GPLv3

### PR DESCRIPTION
**Pull request by MrGlockenspiel**
All significant contributors need to approve this for it to take effect

### CODE REVIEW

**Comment by asoji** [comment]
I approved even tho I've only contributed to 1 branch

**Comment by OneYellowLemon** [comment]
I, OneYellowLemon, agree to activate-linux being relicensed under the GPLv3 license

**Comment by aprunge** [comment]
This is so utterly epic I can't stop myself from approving.

**Comment by ReperakDev** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA384

I, Reperak, consent to my contributions to https://github.com/MrGlockenspiel/activate-linux to be relicensed under the GPLv3
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCQAdFiEEcHdO1r2Z8vAdAPAT7vhhCUL2/iIFAmKEXAUACgkQ7vhhCUL2
/iL2wRAAokD8L7+D5IFO8NR7aeviMGmDdhGTYUQW80IZ6UvsQ9AdaAD8Z1RIP7Or
bIlGssVMnVl2YQ1mkexpdrzgLXXcWar6oNh92gZiObhaQFu8tD8a4oTtyR6N95fT
YUogGLGfJyl/lFH0Rpd3uH0or/g+giiVascYtYe200s4GnslqRXYW8torv0ine01
wOwkPFpBbAs+xt7KfyiNRH6jAbYjetpnsaGHuOofCvfJSg4IfPcOdv9MnlfuqmRg
DUlwzqIZYEh1FPcLRe9maqQ4Oac9tBFcFpBZ+AFOPn6fgpH97FA83HPRR+cx7H+T
vcawXPt853LL6UfinTPKZ5VvDLajEWGaP0U9y7Ju4ldzE6vz8dZH6bENguafD/YV
CqObwzYsQo9+Ovi+t535GrOAyNNGnBjDGFOV6EYRJAqs4YYSVlxDl97zunBhjJF2
jnfivRewRrucqOPwchH+nCZiXqNATbuRcm/BXcRbrNdtGWUEhDc4FhfIWX0dXixr
swYpujf1lp5fHFAY2Iwik3UGOlk792ce9IJXvFr1zBTPbkNzoEDu1t9oGs2GyEI2
9/vrwDUOXkZqGKDPButDqVy7W3qA6mDUih4GKf2xAQQUOyGyJV8wdjbmODsTM1Hv
zwweDWfFiWdE6/+k+IiG0OdnYHN0IQOXAJD9c0Y7/eoGgNsZZM0=
=ONXz
-----END PGP SIGNATURE-----
```

**Comment by OneYellowLemon** [comment]
> I approve even tho I've only contributed to 1 branch

@asoji Please follow the wording I used in mine. Legal bureaucracy ¯\_(ツ)_/¯

**Comment by ReperakDev** [comment]
> > I approve even tho I've only contributed to 1 branch
> 
> @asoji Please follow the wording I used in mine. Legal bureaucracy ¯_(ツ)_/¯

:nerd_face:

**Comment by asoji** [comment]
Edited.

**Comment by OneYellowLemon** [comment]
@Ruby-Dragon @WoMspace @ohno9119 @tamara-schmitz @ForumPlayer @NickGenghar @10maurycy10 @lattera @athendrix @Piraty @WebFreak001 @Cake967

I'm going to go ahead and mention all of you so you see this 😉

**Comment by Ruby-Dragon** [comment]
I approve

**Comment by NickGenghar** [comment]
I, NickGenghar, agree to activate-linux being re-licensed under the GPLv3 license.

**Comment by OneYellowLemon** [comment]
> I approve

Please see my edited comment above :)

**Comment by 10maurycy10** [comment]
I, 10maurycy10, agree to activate-linux being relicensed under the GPLv3 license.

**Comment by ReperakDev** [comment]
btw if this gets merged you gotta add [the drip](https://www.gnu.org/graphics/license-logos.html) to the readme

**Comment by asoji** [comment]
@MrGlockenspiel maybe add that to the PR while you're at it

wait does this have to be added to the other dumb whatiswrongwithyoupeoplepleasegooutsideandtouchsomegrassandmaybegetsomebitches branch too

**Comment by MrGlockenspiel** [comment]
it technically does not and that branch can remain on the based license
+we would have to get every contributor for that branch to agree separately i believe

**Comment by asoji** [comment]
P AI N

**Comment by ReperakDev** [comment]
> it technically does not and that branch can remain on the based license +we would have to get every contributor for that branch to agree separately i believe

there's literally two contributors and one is yourself

**Comment by asoji** [comment]
true 😎

**Comment by MrGlockenspiel** [comment]
oh I thought there were more
oh well

**Comment by MrGlockenspiel** [comment]
anyway we have GPL drip now

**Comment by asoji** [comment]
> oh I thought there were more oh well

my dude that branch literally changes it to

> Activate ur mom
> Go to Settings to activate deez nuts.

so it was always a 2 contributor joke branch at best 😆

**Comment by 10maurycy10** [comment]
> my dude that branch literally changes it to

> > Activate ur mom
> > Go to Settings to activate deez nuts.

> so it was always a 2 contributor joke branch at best 😆

my change was chaning the perms on one file.

**Comment by ReperakDev** [comment]
> anyway we have GPL drip now

You gotta have the logo, its so much better than those done-to-death badges

**Comment by athendrix** [comment]
My contribution is hardly anything I'd consider "major" but nevertheless, I, athendrix, agree to activate-linux being relicensed under the GPLv3 license

**Comment by MrGlockenspiel** [comment]
> > anyway we have GPL drip now
> 
> You gotta have the logo, its so much better than those done-to-death badges

The images are not split and i am lazy

**Comment by lattera** [comment]
Though I'm quite biased towards the 2-clause BSD license, I don't have much of an opinion on licensing choice for this project. I approve of switching my code contributions to this project to a copyleft license like the GPL.

**Comment by ohno9119** [comment]
I, ohno9119, agree to activate-linux being relicensed under the GPLv3 license

**Comment by Newbytee** [comment]
You could also dual licence it as GPL-3.0 and Based if you want to keep the funny.

**Comment by bluelhf** [comment]
I, bluelhf, agree to activate-linux being relicensed under the GPLv3 license

**Comment by tamara-schmitz** [comment]
I, tamara-schmitz, agree to activate-linux being relicensed under the GPLv3 license

**Comment by WebFreak001** [comment]
I, WebFreak, agree to activate-linux being relicensed under the GPLv3 license

**Comment by WoMspace** [comment]
Can someone explain why we're moving from Based License to GPL3? I think Glock said on discord it's due to some funk with Based but what exactly is it?

**Comment by Newbytee** [comment]
For one thing, Based Licence is a nonfree licence which prevents this from being packaged in many distributions.

**Comment by WoMspace** [comment]
Ah yes I just saw #76.
I, WoMapace, agree to activate-linux being re-licensed under the GPLv3 license.

**Comment by OneYellowLemon** [comment]
We're down to just four contributors who need to approve still!

@Ruby-Dragon Please edit your comment or post a new one to follow the legal speak everyone else is using 😉

**Comment by Ruby-Dragon** [comment]
Fine, I, Ruby-Dragon, agree to change the Licence of activate-linux to GPLv3

**Comment by Ruby-Dragon** [comment]
Can we just delete the other branch?

**Comment by ReperakDev** [comment]
> Ah yes I just saw #76.
> I, WoMapace, agree to activate-linux being re-licensed under the GPLv3 license.

You spelled your own name wrong L

**Comment by WoMspace** [comment]
> > Ah yes I just saw #76.
> > I, WoMapace, agree to activate-linux being re-licensed under the GPLv3 license.
> 
> You spelled your own name wrong L

Fricking phone autocorrect. Fixed it.

**Comment by ReperakDev** [comment]
LGTM btw. if the remaining contributors havent responded by now they probably dont give a shit

**Comment by TechnologyClassroom** [comment]
I believe @Piraty is the only one with legally significant contributions absent from agreeing. [60++ 67 --](https://github.com/MrGlockenspiel/activate-linux/commit/8ff0df722f6af0f4c5fbbeaa5f88374539c384aa)

**Comment by Ruby-Dragon** [comment]
We should probably update the release after this so it has the correct licence

**Comment by Piraty** [comment]
i'm fine with gpl, would have preferred a permissive license though

**Comment by MrGlockenspiel** [comment]
Ok looks like thats everyone
Merging now

**Comment by ForumPlayer** [comment]
Hold on guys, i didn't had time to check this before, but I agree with the re-licensing (legal statement in the next comment)
There's just a thing @MrGlockenspiel forgot.. to add all the info to the License :/
On lines [644](https://github.com/MrGlockenspiel/activate-linux/pull/79/files#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1dR634), [645](https://github.com/MrGlockenspiel/activate-linux/pull/79/files#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1dR635), and [655](https://github.com/MrGlockenspiel/activate-linux/pull/79/files#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1dR655), all of then on [LICENSE.md](https://github.com/MrGlockenspiel/activate-linux/pull/79/files#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1d).
Even through this, I still agree.

**Comment by TechnologyClassroom** [comment]
@ForumPlayer Lines 644-655 should not be modified in the LICENSE.md file itself and modifying the file will break automatic identification done by GitHub and other forges.  Those are instructions for applying GPL standard license headers to all applicable files that the license covers.

**Comment by ForumPlayer** [comment]
@TechnologyClassroom that's really strange.. I use to edit those lines and GitHub always detected the license correctly.

**Comment by ForumPlayer** [comment]
I, ForumPlayer, agree to activate-linux being relicensed under the GPLv3 license.

[PGP Signed Version](https://github.com/MrGlockenspiel/activate-linux/files/8733003/signed-version.txt) (Key available on [OpenPGP](https://keys.openpgp.org/search?q=fp%40forumplayer.dev) Keyserver)

**Comment by TechnologyClassroom** [comment]
@ForumPlayer Maybe GitHub has corrected after enough people doing just that.  I doubt all forges would catch that.

I do know that you are not supposed to edit the license itself though.  See how [emacs](https://git.savannah.gnu.org/cgit/emacs.git/tree/COPYING) does not edit the license itself, but only changes that text in the [standard](https://git.savannah.gnu.org/cgit/emacs.git/tree/src/bignum.c) [license](https://git.savannah.gnu.org/cgit/emacs.git/tree/autogen.sh) [headers](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/custom.el) of individual files.

**Pull request merged**
