### PR TITLE
Add it_IT locale

### PR DESCRIPTION
**Pull request by Ale32bit**
This PR adds the Italian localization.

### CODE REVIEW

**Comment by Ruby-Dragon** [comment]
once the presets PR is merged, this will not work anymore

**Comment by MrGlockenspiel** [comment]
im fixing it with the new preset system now

**Comment by MrGlockenspiel** [comment]
im pretty sure i fixed it, but i have no idea how to test another language so if someone can check it or tell it how it would be appreciated

**Comment by Ruby-Dragon** [comment]
you can test another language by changing your region to another region, thats how I tested French and Dutch and it worked. Hope you can read Italian!

**Pull request merged**
