### PR TITLE
[ci skip] Format README.md

### PR DESCRIPTION
**Pull request by OneYellowLemon**
I formatted README.md so it's easier to read & understand.

### CODE REVIEW

**Comment by EzraWolf** [comment]
dont do it it will explode

**Comment by Ruby-Dragon** [comment]
the notice about the executable being in /bin is not macOS specific and should be placed in the Linux build instructions too.

**Comment by MrGlockenspiel** [comment]
Yeah
Just fix that and I'll merge it, everything else looks good

**Comment by MrGlockenspiel** [comment]
>duplicate message in README

wasted bytes

**Pull request merged**
