### PR TITLE
Implement macOS compatibility

### PR DESCRIPTION
**Pull request by 89mpxf**

### CODE REVIEW

**Comment by Ruby-Dragon** [comment]
There is probably a better way to implement macos compatibility than to just make an entire different source file.

**Comment by 89mpxf** [comment]
Okay but realistically this is a joke program we're talking about do you really think we should be putting the upmost performance and efficiency into it or do you think that maybe you should stop being a little bitch and have some fun

**Comment by MrGlockenspiel** [comment]
Yes we should put the utmost performance and efficiency into it
Otherwise I would be writing it in python

`ifdef __APPLE__` exists :trollface:

**Comment by MrGlockenspiel** [comment]
Anyway yeah I am in the process of fixing this and reorganizing a bit

**Comment by MrGlockenspiel** [comment]
Done in commit [4279108](https://github.com/MrGlockenspiel/activate-linux/commit/4279108b219e10d27b77e6baecf339ee3cdbd083)
Somebody is going to have to test it though, because I can't

**Pull request closed without merging**
